# Generated by Django 5.2.9 on 2025-12-25 14:13

import content_pipeline.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEventModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('raw_content', models.TextField()),
                ('source_url', models.URLField(max_length=1000)),
                ('published_at', models.DateTimeField()),
                ('extracted_facts', content_pipeline.models.ListField(default=list)),
                ('categories', content_pipeline.models.ListField(default=list)),
                ('geographic_locations', content_pipeline.models.ListField(default=list)),
                ('age_appropriateness', models.CharField(blank=True, max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('processing_status', models.CharField(default='RAW', max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'news_events',
                'ordering': ['-published_at'],
            },
        ),
    ]
