# Generated by Django 5.2.9 on 2026-02-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newseventmodel",
            name="content_elements",
            field=models.JSONField(default=None, null=True),
        ),
    ]
