# Generated by Django 5.2.9 on 2026-02-01 06:56

import content_pipeline.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content_pipeline", "0002_newseventmodel_content_elements"),
    ]

    operations = [
        migrations.AddField(
            model_name="newseventmodel",
            name="discussion_questions",
            field=content_pipeline.models.ListField(default=list),
        ),
    ]
