# Generated by Django 5.2.9 on 2026-02-19 19:38

import content_pipeline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_pipeline", "0003_newseventmodel_discussion_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="newseventmodel",
            name="fun_facts",
            field=content_pipeline.models.ListField(default=list),
        ),
        migrations.AddField(
            model_name="newseventmodel",
            name="video_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
